workflows: remove bit from folder and cache

diff --git a/.github/workflows/mpv.yml b/.github/workflows/mpv.yml
--- a/.github/workflows/mpv.yml
+++ b/.github/workflows/mpv.yml
@@ -118,19 +118,19 @@ jobs:
         id: lookup_toolchain
         uses: actions/cache/restore@v4.3.0
         with:
-          path: ${{ github.workspace }}/mpv-winbuild-cmake/build${{ matrix.bit }}
-          key: toolchain-${{ inputs.compiler }}-build${{ matrix.bit }}-${{ env.cache_suffix }}
+          path: ${{ github.workspace }}/mpv-winbuild-cmake/build
+          key: toolchain-${{ inputs.compiler }}-build-${{ env.cache_suffix }}
           restore-keys: |
-            toolchain-${{ inputs.compiler }}-build${{ matrix.bit }}-
+            toolchain-${{ inputs.compiler }}-build-
           lookup-only: true
       - name: Lookup Build Cache
         id: lookup_build
         uses: actions/cache/restore@v4.3.0
         with:
-          path: ${{ github.workspace }}/mpv-winbuild-cmake/build${{ matrix.bit }}
-          key: ${{ inputs.compiler }}-build${{ matrix.bit }}-${{ env.cache_suffix }}
+          path: ${{ github.workspace }}/mpv-winbuild-cmake/build
+          key: ${{ inputs.compiler }}-build-${{ env.cache_suffix }}
           restore-keys: |
-            ${{ inputs.compiler }}-build${{ matrix.bit }}-
+            ${{ inputs.compiler }}-build-
           lookup-only: true
           
       - name: Generate cache key
@@ -140,13 +140,13 @@ jobs:
           script: |
             let toolchain_restore_key="${{ steps.lookup_toolchain.outputs.cache-matched-key }}";
             let build_restore_key="${{ steps.lookup_build.outputs.cache-matched-key }}";
-            let build_save_key="${{ inputs.compiler }}-build${{ matrix.bit }}-${{ env.cache_suffix }}";
+            let build_save_key="${{ inputs.compiler }}-build-${{ env.cache_suffix }}";
             let key_suffix= "${{ env.cache_suffix }}"
             let restore_suffix= ""; // if only want to match primaryKey, set a value which make restore-keys can't hit
             
             // If toolchain cache exist, compare version of toolchain and build
             if (toolchain_restore_key) {
-              const toolchain_version = toolchain_restore_key.split("-build${{ matrix.bit }}-").at(-1);
+              const toolchain_version = toolchain_restore_key.split("-build-").at(-1);
               core.exportVariable( `toolchain_version`, toolchain_version );
 
               build_save_key += `(${toolchain_version})`;
@@ -172,9 +172,9 @@ jobs:
         uses: actions/cache/restore@v4.3.0
         with: 
           path: ${{ github.workspace }}/mpv-winbuild-cmake/clang_root
-          key: ${{ matrix.bit }}-clang_root-${{ env.key_suffix }}
+          key: clang_root-${{ env.key_suffix }}
           restore-keys: |
-            ${{ matrix.bit }}-clang_root-${{ env.restore_suffix }}
+            clang_root-${{ env.restore_suffix }}
 
       - name: Restore Rust Cache
         uses: actions/cache/restore@v4.3.0
@@ -195,13 +195,13 @@ jobs:
         if: ${{ env.toolchain_restore_key != '' }}
         uses: actions/cache/restore@v4.3.0
         with:
-          path: ${{ github.workspace }}/mpv-winbuild-cmake/build${{ matrix.bit }}
+          path: ${{ github.workspace }}/mpv-winbuild-cmake/build
           key: ${{ env.toolchain_restore_key }}
       - name: Restore Build Cache
         if: ${{ inputs.needclean != true && env.build_restore_key != '' }}
         uses: actions/cache/restore@v4.3.0
         with:
-          path: ${{ github.workspace }}/mpv-winbuild-cmake/build${{ matrix.bit }}
+          path: ${{ github.workspace }}/mpv-winbuild-cmake/build
           key: ${{ env.build_restore_key }}
 
       - name: Set up ccache
@@ -210,7 +210,7 @@ jobs:
           update_packager_index: false
           install_ccache: false
           store_cache: ${{inputs.no_save_cache != true }}
-          override_cache_key: ccache-build${{ matrix.bit }}-${{ inputs.compiler }}
+          override_cache_key: ccache-build-${{ inputs.compiler }}
           ccache_options: |
             cache_dir=${{ github.workspace }}/.ccache
             max_size=500M
@@ -223,14 +223,13 @@ jobs:
         continue-on-error: true
         run: |
           cd mpv-winbuild-cmake
-          bit="${{ matrix.bit }}"
           compiler="${{ inputs.compiler }}"
           gitdir=$(pwd)
           clang_root=$(pwd)/clang_root
           buildroot=$(pwd)
           srcdir=$(pwd)/src_packages
           
-          builddir=$buildroot/build$bit
+          builddir=$buildroot/build
           arch="x86_64"
           retry-tool() {
             local RETRY_COUNTER=0
@@ -255,24 +254,23 @@ jobs:
           clang_root=$(pwd)/clang_root
           buildroot=$(pwd)
           srcdir=$(pwd)/src_packages
-          bit="64"
           arch="x86_64"
           compiler="clang"
           mkdir -p release
 
-          cmake -Wno-dev --fresh -DTARGET_ARCH=$arch-w64-mingw32 -DCOMPILER_TOOLCHAIN=$compiler -DCMAKE_INSTALL_PREFIX=$clang_root -DMINGW_INSTALL_PREFIX=$buildroot/build$bit/install/$arch-w64-mingw32 -DCLANG_PACKAGES_LTO=ON $extra_option -DENABLE_CCACHE=ON -DSINGLE_SOURCE_LOCATION=$srcdir -DRUSTUP_LOCATION=$buildroot/install_rustup -G Ninja -H$gitdir -B$buildroot/build$bit
-          ninja -C $buildroot/build$bit download || true
-          ninja -C $buildroot/build$bit update
-          ninja -C $buildroot/build$bit mpv-fullclean
-          ninja -C $buildroot/build$bit mpv
-          if [ -n "$(find $buildroot/build$bit -maxdepth 1 -type d -name "mpv*" -print -quit)" ] ; then
-              echo "Successfully compiled $bit-bit. Continue"
+          cmake -Wno-dev --fresh -DTARGET_ARCH=$arch-w64-mingw32 -DCOMPILER_TOOLCHAIN=$compiler -DCMAKE_INSTALL_PREFIX=$clang_root -DMINGW_INSTALL_PREFIX=$buildroot/build/install/$arch-w64-mingw32 -DCLANG_PACKAGES_LTO=ON $extra_option -DENABLE_CCACHE=ON -DSINGLE_SOURCE_LOCATION=$srcdir -DRUSTUP_LOCATION=$buildroot/install_rustup -G Ninja -H$gitdir -B$buildroot/build
+          ninja -C $buildroot/build download || true
+          ninja -C $buildroot/build update
+          ninja -C $buildroot/build mpv-fullclean
+          ninja -C $buildroot/build mpv
+          if [ -n "$(find $buildroot/build -maxdepth 1 -type d -name "mpv*" -print -quit)" ] ; then
+              echo "Successfully compiled mpv. Continue"
           else
-              echo "Failed compiled $bit-bit. Stop"
+              echo "Failed compiled mpv. Stop"
               exit 1
           fi
 
-          mv $buildroot/build$bit/mpv* $gitdir/release
+          mv $buildroot/build/mpv* $gitdir/release
           cd $gitdir/release
           for dir in ./mpv*; do
               if [ -d $dir ]; then
@@ -281,18 +279,17 @@ jobs:
               fi
           done
           cd ..
-          sudo rm -rf $buildroot/build$bit/mpv-*
-          sudo chmod -R a+rwx $buildroot/build$bit
-
+          sudo rm -rf $buildroot/build/mpv-*
+          sudo chmod -R a+rwx $buildroot/build
       - name: Collect logs
         if: ${{ always() }}
         run: |
-          sudo 7z a logs.7z $(find mpv-winbuild-cmake/build${{ matrix.bit }} -type f -iname "*-*.log" -or -wholename "*/ffbuild/config.log")
+          sudo 7z a logs.7z $(find mpv-winbuild-cmake/build -type f -iname "*-*.log" -or -wholename "*/ffbuild/config.log")
       - name: upload logs
         uses: actions/upload-artifact@v5
         if: ${{ always() }}
         with:
-          name: ${{ matrix.bit }}_logs
+          name: logs
           path: logs.7z
 
       - name: "Get artifacts' name and path"
@@ -324,7 +321,7 @@ jobs:
         uses: actions/cache/save@v4.3.0
         with: 
           path: ${{ github.workspace }}/mpv-winbuild-cmake/clang_root
-          key: ${{ matrix.bit }}-clang_root-${{ env.cache_suffix }}
+          key: clang_root-${{ env.cache_suffix }}
       - name: Save Sources Cache
         if: ${{ inputs.no_save_cache != true }}
         uses: actions/cache/save@v4.3.0
@@ -341,7 +338,7 @@ jobs:
         if: ${{ inputs.no_save_cache != true }}
         uses: actions/cache/save@v4.3.0
         with:
-          path: ${{ github.workspace }}/mpv-winbuild-cmake/build${{ matrix.bit }}
+          path: ${{ github.workspace }}/mpv-winbuild-cmake/build
           key: ${{ env.build_save_key }}
 
       - name: "Job summary"
@@ -426,7 +423,7 @@ jobs:
             [upstream_local_hash, upstream_remote_hash, upstream_status, upstream_remote] = await repo_info(upstreamDir)
             const upstream_url = getCommitUrl(upstream_remote_hash, upstream_remote);
 
-            const exec_path = path.join(upstreamDir,'build${{ matrix.bit }}','exec');
+            const exec_path = path.join(upstreamDir,'build','exec');
             const compiler_version = (await myExec(`${exec_path}`,["clang","--version"])).split('\n')[0];
                         
             core.summary
@@ -556,9 +553,9 @@ jobs:
         id: toolchain
         uses: ./action/resave_cache
         with:
-          path: ${{ github.workspace }}/mpv-winbuild-cmake/build${{ matrix.bit }}
-          key: toolchain-${{ inputs.compiler }}-build${{ matrix.bit }}-
-          restore-keys: toolchain-${{ inputs.compiler }}-build${{ matrix.bit }}-
+          path: ${{ github.workspace }}/mpv-winbuild-cmake/build
+          key: toolchain-${{ inputs.compiler }}-build-
+          restore-keys: toolchain-${{ inputs.compiler }}-build-
 
       - name: Generate cache key
         id: generate_key
@@ -568,7 +565,7 @@ jobs:
             let toolchain_restore_key="${{ steps.toolchain.outputs.cache-matched-key }}";
             
             if (toolchain_restore_key) {
-              const toolchain_version = toolchain_restore_key.split("-build${{ matrix.bit }}-").at(-1);
+              const toolchain_version = toolchain_restore_key.split("-build-").at(-1);
               core.exportVariable( `toolchain_version`, toolchain_version );
             }
 
@@ -578,8 +575,8 @@ jobs:
         uses: ./action/resave_cache
         with: 
           path: ${{ github.workspace }}/mpv-winbuild-cmake/clang_root
-          key: ${{ matrix.bit }}-clang_root-${{ env.toolchain_version }}
-          restore-keys: ${{ matrix.bit }}-clang_root-${{ env.toolchain_version }}
+          key: clang_root-${{ env.toolchain_version }}
+          restore-keys: clang_root-${{ env.toolchain_version }}
           
   cache_llvm:
     name: keep llvm cache alive
